"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function BillingPage() {
  const [plan, setPlan] = useState<"free" | "pro">("free"); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/billing").then((response) => response.json()).then((result) => setPlan(result.billing?.plan || "free")); }, []);
  async function changePlan(nextPlan: "free" | "pro") { setLoading(true); setMessage(""); const response = await fetch("/api/billing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ plan: nextPlan }) }); if (response.ok) { setPlan(nextPlan); setMessage(nextPlan === "pro" ? "Your workspace is now on Growth. Enjoy the extra room." : "Your workspace is back on Starter."); } setLoading(false); }
  const plans = [{ id: "free" as const, name: "Starter", price: "$0", description: "For exploring what your knowledge can do.", features: ["3 knowledge sources", "50 messages / month", "5 MB per file", "Embeddable widget"] }, { id: "pro" as const, name: "Growth", price: "$29", description: "For teams ready to make support effortless.", features: ["50 knowledge sources", "2,000 messages / month", "15 MB per file", "Remove Helply branding", "Custom widget styling"] }];
  return <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-10 lg:py-12"><p className="text-sm text-muted">Plans that grow with your knowledge</p><div className="flex items-end justify-between gap-4"><h1 className="mt-1 text-3xl font-bold tracking-tight">Billing</h1><Badge tone="success">{plan} plan active</Badge></div>{message ? <p className="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-success">{message}</p> : null}<div className="mt-8 grid gap-4 md:grid-cols-2">{plans.map((item) => <Card key={item.id} className={item.id === "pro" ? "ring-2 ring-accent" : ""}><CardHeader><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{item.name}</h2>{item.id === "pro" ? <Badge>Popular</Badge> : null}</div><p className="mt-2 text-sm text-muted">{item.description}</p><p className="mt-6 text-4xl font-bold">{item.price}<span className="text-sm font-normal text-muted"> / month</span></p></CardHeader><CardContent><Button className="w-full" variant={item.id === plan ? "secondary" : "primary"} disabled={item.id === plan} loading={loading} onClick={() => void changePlan(item.id)}>{item.id === plan ? "Current plan" : `Switch to ${item.name}`}</Button><ul className="mt-6 space-y-3 border-t border-border pt-5 text-sm">{item.features.map((feature) => <li key={feature} className="flex gap-2"><span className="text-accent">✓</span><span>{feature}</span></li>)}</ul></CardContent></Card>)}</div><p className="mt-6 text-center text-xs text-muted">Demo billing only. No payment details are collected.</p></div>;
}
